### ISSUE TITLE
Order of APIkeys should be the same in os-webrtc-janus.ini and secrets files

### ISSUE THREAD

**Issue by Misterblue** [Misterblue/os-webrtc-janus#12]

**Comment by EagleCx** [comment]
So in my oppinion I think it is going to be like this. to make less errors.

os-webrtx-janus.ini

[JanusWebRtcVoice]
    JanusGatewayURI=http://example.janus.org:14223/voice
    APIToken=APITokenIsHidden
    JanusGatewayAdminURI=http://example.janus.org:14225/voiceAdmin
    AdminAPIToken=AdminsTokenIsHidden


In Project "os-webrtc-janus-docker"

secrets

JS_API_TOKEN=APITokenIsHidden
JS_ADMIN_TOKEN=AdminsTokenIsHidden

**Comment by Misterblue** [comment]
Resolved by commit 4d8f8bb8aed8f7cf9b93d51af15a7883221626f0
