### ISSUE TITLE
region message for REGION WEBRTC VOICE.

### ISSUE THREAD

**Issue by EagleCx** [Misterblue/os-webrtc-janus#15]
15:35:11 - [REGION WEBRTC VOICE]:[ProvisionVoice]: voice_server_type is not 'webrtc'. Request: {"voice_server_type":"vivox"}

Not sure if this is a problem or where to address this, if it is the viewer setting in this case FS latest was used.

**Comment by Misterblue** [comment]
The Firestorm viewer sends a ProvisionVoice request with voice_service_type as "vivox". os-webrtc-janus returns an error. Firestorm then sends a ProvisionVoice request with voice_service_type being "webrtc". 

I presume that Firestorm (and maybe other TPVs) are supporting both Vivox and WebRTC and thus initially ask about Vivox support and, when an error is received, continues with WebRTC.

This is not an error and seems to be just how things work for the TPVs.
